In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("D:/Python/DataScieneML/Supervised ML/LR/Diabetes/training_diabetes.csv")
df

,# age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,Y
0,-0.049105,-0.044642,0.160855,-0.046985,-0.029088,-0.019790,-0.047082,0.034309,0.028017,0.011349,346.0
1,-0.070900,0.050680,-0.089197,-0.074528,-0.042848,-0.025739,-0.032356,-0.002592,-0.012908,-0.054925,104.0
2,0.001751,-0.044642,-0.070875,-0.022885,-0.001569,-0.001001,0.026550,-0.039493,-0.022512,0.007207,49.0
3,0.048974,0.050680,0.081097,0.021872,0.043837,0.064134,-0.054446,0.071210,0.032433,0.048628,180.0
4,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014956,0.011349,110.0
...,...,...,...,...,...,...,...,...,...,...,...
326,0.012648,-0.044642,-0.020218,-0.015999,0.012191,0.021233,-0.076536,0.108111,0.059881,-0.021788,233.0
327,0.019913,-0.044642,-0.057941,-0.057314,-0.001569,-0.012587,0.074412,-0.039493,-0.061177,-0.075636,63.0
328,0.023546,-0.044642,0.070319,0.025315,-0.034592,-0.014466,-0.032356,-0.002592,-0.019197,-0.009362,288.0
329,0.016281,0.050680,0.072474,0.076958,-0.008449,0.005575,-0.006584,-0.002592,-0.023645,0.061054,131.0
330,-0.009147,0.050680,-0.030996,-0.026328,-0.011201,-0.001001,-0.021311,-0.002592,0.006209,0.027917,42.0

In [3]:
data=df.values
data

array([[-4.91050164e-02, -4.46416365e-02,  1.60854917e-01, ...,
         2.80165065e-02,  1.13486232e-02,  3.46000000e+02],
       [-7.09002471e-02,  5.06801187e-02, -8.91974838e-02, ...,
        -1.29079423e-02, -5.49250874e-02,  1.04000000e+02],
       [ 1.75052192e-03, -4.46416365e-02, -7.08746786e-02, ...,
        -2.25121719e-02,  7.20651633e-03,  4.90000000e+01],
       ...,
       [ 2.35457526e-02, -4.46416365e-02,  7.03187031e-02, ...,
        -1.91970476e-02, -9.36191133e-03,  2.88000000e+02],
       [ 1.62806757e-02,  5.06801187e-02,  7.24743273e-02, ...,
        -2.36445576e-02,  6.10539062e-02,  1.31000000e+02],
       [-9.14709343e-03,  5.06801187e-02, -3.09956318e-02, ...,
         6.20931562e-03,  2.79170509e-02,  4.20000000e+01]])

In [4]:
X=data[:,0:10]
Y=data[:,10]

In [5]:
from sklearn.linear_model import LinearRegression as LR

In [6]:
alg=LR()

In [7]:
alg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
Y_train_predict=alg.predict(X)

In [9]:
print(alg.score(X,Y_train_predict))

1.0

In [11]:
test=pd.read_csv("D:/Python/DataScieneML/Supervised ML/LR/Diabetes//test_diabetes.csv")
test

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10
0,-0.078165,-0.044642,-0.073030,-0.057314,-0.084126,-0.074277,-0.024993,-0.039493,-0.018118,-0.083920
1,-0.030942,0.050680,0.001339,-0.005671,0.064477,0.049416,-0.047082,0.108111,0.083797,0.003064
2,-0.005515,0.050680,0.001339,-0.084857,-0.011201,-0.016658,0.048640,-0.039493,-0.041180,-0.088062
3,-0.020045,-0.044642,-0.084886,-0.026328,-0.035968,-0.034194,0.041277,-0.051671,-0.082381,-0.046641
4,-0.034575,-0.044642,-0.037463,-0.060757,0.020446,0.043466,-0.013948,-0.002592,-0.030751,-0.071494
...,...,...,...,...,...,...,...,...,...,...
106,0.005383,-0.044642,0.049840,0.097616,-0.015328,-0.016345,-0.006584,-0.002592,0.017037,-0.013504
107,0.009016,-0.044642,-0.012673,0.028758,-0.018080,-0.005072,-0.047082,0.034309,0.023375,-0.005220
108,0.019913,-0.044642,-0.034229,0.055153,0.067229,0.074155,-0.006584,0.032833,0.024725,0.069338
109,0.016281,0.050680,0.009961,-0.043542,-0.096510,-0.094632,-0.039719,-0.039493,0.017037,0.007207
110,0.023546,0.050680,-0.037463,-0.046985,-0.091006,-0.075530,-0.032356,-0.039493,-0.030751,-0.013504

In [12]:
X_test=test.values

In [13]:
Y_test_predict=alg.predict(X_test)

Y_test_predict=np.round(Y_test_predict,5) #round to five digits

test_df=pd.DataFrame(Y_test_predict)

test_df.to_csv("D:/Python/DataScieneML/Supervised ML/LR/Diabetes/test_predict_diabetes.csv",index=False,header=('Diabetes'))

In [14]:
print(alg.score(X_test,Y_test_predict))

0.9999999999999968